baseURL = "https://sheeta38.github.io/"
author = "Sheeta Sakuramachi"
title = "桜町記録片"
theme = "jeffprod"
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
