baseURL = "https://sheeta38.github.io/blog/"
author = "sheeta38"
title = "桜町記録片"
theme = "jeffprod"
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja"

# Disable comments by leaving disqusShortname empty
disqusShortname = "your disqus shortname"
copyright = "Copyright © 2019, Sheeta Sakuramachi"
canonifyURLS = true
paginate = 12

[permalinks]
post = "/:year/:filename"

[taxonomies]
tag = "tags"
archive = "archives"
